apiVersion: v1
entries:
  loki:
  - appVersion: 0.0.1
    created: 2019-04-09T21:51:03.697306913Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 48843edc2ac4ba743d09d19d5d4e56a72ecbdcc113ee20da0ba5fbc1e74c5342
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-0.6.0.tgz
    version: 0.6.0
  loki-stack:
  - appVersion: 0.0.1
    created: 2019-04-09T21:51:03.697966775Z
    description: 'Loki: like Prometheus, but for logs.'
    digest: 3534918d7768c07c7aa957fcac55808f60d3845fea630d32bb3af48ab5d09bd2
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: loki-stack
    sources:
    - https://github.com/grafana/loki
    urls:
    - loki-stack-0.6.0.tgz
    version: 0.6.0
  promtail:
  - appVersion: 0.0.1
    created: 2019-04-09T21:51:03.698355313Z
    description: Responsible for gathering logs and sending them to Loki
    digest: 0f86675e17e646d12e0e6c62d44ccd1139ae75f523f0f191c19a018bd76b46a2
    engine: gotpl
    home: https://grafana.com/loki
    icon: https://github.com/grafana/loki/raw/master/docs/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: promtail
    sources:
    - https://github.com/grafana/loki
    urls:
    - promtail-0.6.0.tgz
    version: 0.6.0
generated: 2019-04-09T21:51:03.696808335Z
